/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shark_androidinlinehook_MainActivity */

#ifndef _Included_com_shark_androidinlinehook_MainActivity
#define _Included_com_shark_androidinlinehook_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shark_androidinlinehook_MainActivity
 * Method:    startInlineHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_shark_androidinlinehook_MainActivity_startInlineHook
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
